env:
  global:
  - secure: JjbU69ZIQ63AoiN9iBwg3QdbVOmV/mJKdv62CjaliD1iP7Szm0mr8ZZ3zpquxdi+JCVzBqc9nQOmKBtSc+DAK3dtFnr/zq6kboSEexzj92orBgsB4fLyJKky8I0POTLyv/6CGEWKfuF1g1XFjHou/8DQLc6YQ6JSn/lIojPXuJrawb7Dz9HXq87SAZH43m5UPnev0JhlI1ePZiWPPPsgeDKCewioUBWafjx1O6NlI3Ael093HYlST+RgzW4mAWK1j3/fAHLlQlOn6yW+VvZhyaqToQ0cyqM0GQYIwo53q/ssjiUeaiEQKI7qpH/zhxfHaRJ0qfHrBxnMf69WC08V1DjlBuUwKOuWDU9VxeCcXFYxHdPApSmw68C5bMr7baaYeHmUrpeldox6gFyElxj8QLiFAFIEC4Qi3x24m8er8FtP8dPgSyfttBdF6znAPQFDKWPA4XuIN2x9IARbITElcH0tEAg8YmkK0ImCANV3x/gzMlRSyEiUzI3o+IYtmf66xa4yvW2ldCfFWaTAPIbVSPOKHCm+SFZEhfP8YbagTpzJGkHEmuG7ezMmBkN/F12jwNS1zE0w4KDF0TvaRjgzltawvKmuE5fy9pp3QHGy6m5W+b8v/NwneM4f7EifXXwMNAAxEbiFwSEaZHqNQaodAq/QIdBKqv0NJfbj+UJD08k=
  - DOCKER_USER=khalidashraf
  - secure: WrccS5O4eSH8/HKUukA+cJxa+2wCkj/f4lYgWBeGFpoX2xFVICYiYfp5cHSL6VYFCieq24LCufdhB7JvJ+JWjbmmrElC4aluNSfRgpwQBlN7OTVmMwCEzII3Uu8tIww8md7/mIdG/6YBSDPWFPo17tFI69bx0t1AXUWts3WLHTuVilp3EFrlZXpnUKR3d91hSQ+9hG3UnGP8fLAlC/D2b/3gVuCZ7tv9zrcQWh4zFDYIjxT6SKeiOOwwlC9i9qGb6pcDxFxHjMVgXtLU1ue6Gh9KPXyd3WRyPmKd/mxrH8qCw6tad+/gsSk25Vkue+dKQs8F4+Qkc8L2IwcdwIq8ty12Wfu2Wc7GSC7mSCdwq1AySRqOVcAWIlCSGPHP7Rv3bC7RQ0i1CQaRlV4ch/3LfXBva1DfFG01gAKqimmwvT0yCxN8g+MT7pnYfSofnCFFZsuCpahyT1B36wkB9hBAxeUYRO1vi1+scu48J++YfXBqXyvgZm+CnsHv1UsWAYdt5YT1VRnOumJ564wZS64x4MUyKqsFDZvdpB6VICmtwJYk2fcQ4UQ1jL6Hvkezqh7BJew1Osw3LSRr3Y/90iywMAF70/bEKS0E3s2xZVVfblxDOEtlBoEFIgNyBR/TX2fQ2Vi2xo9i0gtV8JtFmwUaYnKzmEsckGaTSyruuYAgbjs=
  - HEROKU_APP=khalidashraf-todo-app
services:
- docker
  
script:  
  # Build test image and test the code
  - docker build --target test --tag todo_app:test .
  - docker run --env-file .env.test todo_app:test tests
  - docker run -e SECRET_KEY -e MONGO_USER -e MONGO_PASS -e MONGO_DB todo_app:test tests_e2e

deploy:
  provider: script
  script: bash ./build-deploy.sh
  on:
    branch: master

notifications:
  slack:
    secure: o5cEaHOFMzW435cV5zT/4MaoyHC3X3DS9091yDH6SxwLy6F/rngAy5EwDZ53opq/YdWYyGhlumsiZFfVyI2qpyZSkE2Epk9p35YT0Gdx/x9oad91G8PeyaWSBN2GWfceZ/qBxTfamyACUPr2ItWi7oPw65RnYM/kRcbfmXnxC9bqQcDX0bLWVDRZtVmmsZJ0kNnCwznsBb9gpVV7Vz3ZVhv9QvFoYPyIDdyMT2vlYHu/iQ8FJIX9eKuYuqViklUiwWYIejUqp7892x3m5Bywm7e0Y0NqXmWbXsiW8MizQsn9E6M93Ed4+xNyKWz7f6O7GvVZm1GmdyH5FPB3Nz38FxOy6e4bYC8r399DJISZl0VMYtqDhKndoqRvSpR4tvvmad5x37mAMs2o1IpRc2OQTJ5Rtz54Hqw+gAHa3lvyFuz1QvMjaZnp9zXLy6dJYF6VIJu6FKDKQJwLbiYio18EqkxauxUGM0VB+12JiVds53aXNqlPkqopzhNdCKnSUlKH0yho6SJzzyYRnKG9vOGaIbx88Sf+PrEIYylXdFlsfH/I3bhFMkRN2EoHZpYaaDXPqxk/IXCUHNHU39cuu9CpQYFXt3rlirljBD/o2Oi3oiMXT36jFL37Oc4C3jxiv2cj0LLacgB/e0qwGqhjqjLerKiYPjh1vvdOt9aGvpXcIAA=
  email:
    recipients:
    - khalid.ashraf@hotmail.com
    on_success: never
    on_failure: always
